// apps/web/src/components/layout/sidebar/constants/icon-map.ts
import {
  Activity,
  BarChart3,
  Bell,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  Cog,
  CreditCard,
  Database,
  Eye,
  Factory,
  FileBarChart,
  FileText,
  FolderOpen,
  Globe,
  HardDrive,
  Home,
  Languages,
  LayoutDashboard,
  type LucideIcon,
  Menu,
  Monitor,
  Package,
  PieChart,
  Scale,
  Search,
  Shield,
  Table,
  TestTube,
  TrendingUp,
  User,
  UserCheck,
  Users,
  Wrench,
} from 'lucide-react'

/**
 * Mapping des noms d'icônes vers les composants Lucide
 * Utilisé pour convertir les noms d'icônes stockés en base de données
 * vers les composants React Lucide
 */
export const iconMap: Record<string, LucideIcon> = {
  Home,
  Shield,
  Users,
  Building,
  Building2,
  Bell,
  Activity,
  Calendar,
  Briefcase,
  UserCheck,
  FileBarChart,
  TrendingUp,
  PieChart,
  HardDrive,
  Cog,
  Eye,
  BarChart3,
  CreditCard,
  Database,
  Factory,
  FileText,
  FolderOpen,
  LayoutDashboard,
  Package,
  User,
  Wrench,
  Monitor,
  Languages,
  Table,
  Search,
  Globe,
  // Mappings pour les icônes des routes API
  dashboard: LayoutDashboard,
  admin: Shield,
  company: Building2,
  roles: Shield,
  database: Database,
  translations: Languages,
  notifications: Bell,
  rules: Scale,
  planning: CalendarDays,
  test: TestTube,
  menu: Menu,
}
