/**
 * Injecteur pour cornières (angles)
 * TopSteel ERP - Clean Architecture
 */

import { BaseArticleInjector } from '../core/base-article-injector'
import {
  ArticleFamille,
  type ArticleMetallurgie,
  ArticleStatus,
  ArticleType,
  type CaracteristiquesTechniques,
  UniteStock,
} from '../types/article-injection.types'

interface AngleSpecification {
  type: 'EGAUX' | 'INEGAUX'
  dimensions: string
  cote1: number
  cote2: number
  epaisseur: number
  poids: number // kg/m
  section: number // cm²
  inertiex: number // cm⁴
  inertiey: number // cm⁴
  rayonX: number // cm
  rayonY: number // cm
}

export class AnglesInjector extends BaseArticleInjector {
  private readonly angleSpecifications: AngleSpecification[] = [
    // Cornières à ailes égales
    {
      type: 'EGAUX',
      dimensions: '20x20x3',
      cote1: 20,
      cote2: 20,
      epaisseur: 3,
      poids: 0.89,
      section: 1.13,
      inertiex: 0.4,
      inertiey: 0.4,
      rayonX: 0.59,
      rayonY: 0.59,
    },
    {
      type: 'EGAUX',
      dimensions: '25x25x3',
      cote1: 25,
      cote2: 25,
      epaisseur: 3,
      poids: 1.12,
      section: 1.43,
      inertiex: 0.8,
      inertiey: 0.8,
      rayonX: 0.75,
      rayonY: 0.75,
    },
    {
      type: 'EGAUX',
      dimensions: '25x25x4',
      cote1: 25,
      cote2: 25,
      epaisseur: 4,
      poids: 1.45,
      section: 1.85,
      inertiex: 0.98,
      inertiey: 0.98,
      rayonX: 0.73,
      rayonY: 0.73,
    },
    {
      type: 'EGAUX',
      dimensions: '30x30x3',
      cote1: 30,
      cote2: 30,
      epaisseur: 3,
      poids: 1.36,
      section: 1.74,
      inertiex: 1.42,
      inertiey: 1.42,
      rayonX: 0.9,
      rayonY: 0.9,
    },
    {
      type: 'EGAUX',
      dimensions: '30x30x4',
      cote1: 30,
      cote2: 30,
      epaisseur: 4,
      poids: 1.78,
      section: 2.27,
      inertiex: 1.78,
      inertiey: 1.78,
      rayonX: 0.88,
      rayonY: 0.88,
    },
    {
      type: 'EGAUX',
      dimensions: '35x35x4',
      cote1: 35,
      cote2: 35,
      epaisseur: 4,
      poids: 2.09,
      section: 2.67,
      inertiex: 2.9,
      inertiey: 2.9,
      rayonX: 1.04,
      rayonY: 1.04,
    },
    {
      type: 'EGAUX',
      dimensions: '40x40x4',
      cote1: 40,
      cote2: 40,
      epaisseur: 4,
      poids: 2.42,
      section: 3.08,
      inertiex: 4.47,
      inertiey: 4.47,
      rayonX: 1.2,
      rayonY: 1.2,
    },
    {
      type: 'EGAUX',
      dimensions: '40x40x5',
      cote1: 40,
      cote2: 40,
      epaisseur: 5,
      poids: 2.97,
      section: 3.79,
      inertiex: 5.33,
      inertiey: 5.33,
      rayonX: 1.19,
      rayonY: 1.19,
    },
    {
      type: 'EGAUX',
      dimensions: '45x45x4',
      cote1: 45,
      cote2: 45,
      epaisseur: 4,
      poids: 2.74,
      section: 3.49,
      inertiex: 6.59,
      inertiey: 6.59,
      rayonX: 1.37,
      rayonY: 1.37,
    },
    {
      type: 'EGAUX',
      dimensions: '45x45x5',
      cote1: 45,
      cote2: 45,
      epaisseur: 5,
      poids: 3.38,
      section: 4.31,
      inertiex: 7.84,
      inertiey: 7.84,
      rayonX: 1.35,
      rayonY: 1.35,
    },
    {
      type: 'EGAUX',
      dimensions: '50x50x4',
      cote1: 50,
      cote2: 50,
      epaisseur: 4,
      poids: 3.06,
      section: 3.89,
      inertiex: 9.31,
      inertiey: 9.31,
      rayonX: 1.55,
      rayonY: 1.55,
    },
    {
      type: 'EGAUX',
      dimensions: '50x50x5',
      cote1: 50,
      cote2: 50,
      epaisseur: 5,
      poids: 3.77,
      section: 4.8,
      inertiex: 11.0,
      inertiey: 11.0,
      rayonX: 1.52,
      rayonY: 1.52,
    },
    {
      type: 'EGAUX',
      dimensions: '50x50x6',
      cote1: 50,
      cote2: 50,
      epaisseur: 6,
      poids: 4.47,
      section: 5.69,
      inertiex: 12.6,
      inertiey: 12.6,
      rayonX: 1.49,
      rayonY: 1.49,
    },
    {
      type: 'EGAUX',
      dimensions: '60x60x5',
      cote1: 60,
      cote2: 60,
      epaisseur: 5,
      poids: 4.57,
      section: 5.82,
      inertiex: 19.5,
      inertiey: 19.5,
      rayonX: 1.83,
      rayonY: 1.83,
    },
    {
      type: 'EGAUX',
      dimensions: '60x60x6',
      cote1: 60,
      cote2: 60,
      epaisseur: 6,
      poids: 5.42,
      section: 6.91,
      inertiex: 22.5,
      inertiey: 22.5,
      rayonX: 1.81,
      rayonY: 1.81,
    },
    {
      type: 'EGAUX',
      dimensions: '60x60x8',
      cote1: 60,
      cote2: 60,
      epaisseur: 8,
      poids: 7.09,
      section: 9.03,
      inertiex: 27.7,
      inertiey: 27.7,
      rayonX: 1.75,
      rayonY: 1.75,
    },
    {
      type: 'EGAUX',
      dimensions: '70x70x6',
      cote1: 70,
      cote2: 70,
      epaisseur: 6,
      poids: 6.38,
      section: 8.13,
      inertiex: 35.2,
      inertiey: 35.2,
      rayonX: 2.08,
      rayonY: 2.08,
    },
    {
      type: 'EGAUX',
      dimensions: '70x70x7',
      cote1: 70,
      cote2: 70,
      epaisseur: 7,
      poids: 7.38,
      section: 9.4,
      inertiex: 39.5,
      inertiey: 39.5,
      rayonX: 2.05,
      rayonY: 2.05,
    },
    {
      type: 'EGAUX',
      dimensions: '80x80x6',
      cote1: 80,
      cote2: 80,
      epaisseur: 6,
      poids: 7.34,
      section: 9.35,
      inertiex: 51.8,
      inertiey: 51.8,
      rayonX: 2.35,
      rayonY: 2.35,
    },
    {
      type: 'EGAUX',
      dimensions: '80x80x8',
      cote1: 80,
      cote2: 80,
      epaisseur: 8,
      poids: 9.63,
      section: 12.3,
      inertiex: 64.8,
      inertiey: 64.8,
      rayonX: 2.29,
      rayonY: 2.29,
    },
    {
      type: 'EGAUX',
      dimensions: '90x90x7',
      cote1: 90,
      cote2: 90,
      epaisseur: 7,
      poids: 9.61,
      section: 12.2,
      inertiex: 85.6,
      inertiey: 85.6,
      rayonX: 2.65,
      rayonY: 2.65,
    },
    {
      type: 'EGAUX',
      dimensions: '90x90x8',
      cote1: 90,
      cote2: 90,
      epaisseur: 8,
      poids: 10.9,
      section: 13.9,
      inertiex: 95.2,
      inertiey: 95.2,
      rayonX: 2.62,
      rayonY: 2.62,
    },
    {
      type: 'EGAUX',
      dimensions: '100x100x8',
      cote1: 100,
      cote2: 100,
      epaisseur: 8,
      poids: 12.2,
      section: 15.5,
      inertiex: 129,
      inertiey: 129,
      rayonX: 2.88,
      rayonY: 2.88,
    },
    {
      type: 'EGAUX',
      dimensions: '100x100x10',
      cote1: 100,
      cote2: 100,
      epaisseur: 10,
      poids: 15.0,
      section: 19.2,
      inertiex: 155,
      inertiey: 155,
      rayonX: 2.84,
      rayonY: 2.84,
    },
    {
      type: 'EGAUX',
      dimensions: '120x120x10',
      cote1: 120,
      cote2: 120,
      epaisseur: 10,
      poids: 18.2,
      section: 23.2,
      inertiex: 272,
      inertiey: 272,
      rayonX: 3.42,
      rayonY: 3.42,
    },
    {
      type: 'EGAUX',
      dimensions: '120x120x12',
      cote1: 120,
      cote2: 120,
      epaisseur: 12,
      poids: 21.6,
      section: 27.5,
      inertiex: 316,
      inertiey: 316,
      rayonX: 3.39,
      rayonY: 3.39,
    },
    {
      type: 'EGAUX',
      dimensions: '150x150x12',
      cote1: 150,
      cote2: 150,
      epaisseur: 12,
      poids: 27.3,
      section: 34.8,
      inertiex: 605,
      inertiey: 605,
      rayonX: 4.17,
      rayonY: 4.17,
    },
    {
      type: 'EGAUX',
      dimensions: '150x150x15',
      cote1: 150,
      cote2: 150,
      epaisseur: 15,
      poids: 33.8,
      section: 43.0,
      inertiex: 728,
      inertiey: 728,
      rayonX: 4.11,
      rayonY: 4.11,
    },

    // Cornières à ailes inégales (sélection principale)
    {
      type: 'INEGAUX',
      dimensions: '40x25x4',
      cote1: 40,
      cote2: 25,
      epaisseur: 4,
      poids: 1.93,
      section: 2.46,
      inertiex: 3.28,
      inertiey: 1.12,
      rayonX: 1.15,
      rayonY: 0.67,
    },
    {
      type: 'INEGAUX',
      dimensions: '50x30x5',
      cote1: 50,
      cote2: 30,
      epaisseur: 5,
      poids: 3.06,
      section: 3.9,
      inertiex: 6.96,
      inertiey: 2.09,
      rayonX: 1.34,
      rayonY: 0.73,
    },
    {
      type: 'INEGAUX',
      dimensions: '60x40x5',
      cote1: 60,
      cote2: 40,
      epaisseur: 5,
      poids: 3.86,
      section: 4.92,
      inertiex: 12.8,
      inertiey: 4.54,
      rayonX: 1.61,
      rayonY: 0.96,
    },
    {
      type: 'INEGAUX',
      dimensions: '60x40x6',
      cote1: 60,
      cote2: 40,
      epaisseur: 6,
      poids: 4.57,
      section: 5.82,
      inertiex: 14.7,
      inertiey: 5.14,
      rayonX: 1.59,
      rayonY: 0.94,
    },
    {
      type: 'INEGAUX',
      dimensions: '80x40x6',
      cote1: 80,
      cote2: 40,
      epaisseur: 6,
      poids: 5.52,
      section: 7.03,
      inertiex: 26.8,
      inertiey: 5.09,
      rayonX: 1.95,
      rayonY: 0.85,
    },
    {
      type: 'INEGAUX',
      dimensions: '80x60x6',
      cote1: 80,
      cote2: 60,
      epaisseur: 6,
      poids: 6.38,
      section: 8.13,
      inertiex: 35.2,
      inertiey: 16.2,
      rayonX: 2.08,
      rayonY: 1.41,
    },
    {
      type: 'INEGAUX',
      dimensions: '80x60x8',
      cote1: 80,
      cote2: 60,
      epaisseur: 8,
      poids: 8.35,
      section: 10.6,
      inertiex: 44.0,
      inertiey: 19.4,
      rayonX: 2.04,
      rayonY: 1.35,
    },
    {
      type: 'INEGAUX',
      dimensions: '100x50x6',
      cote1: 100,
      cote2: 50,
      epaisseur: 6,
      poids: 6.85,
      section: 8.73,
      inertiex: 58.8,
      inertiey: 8.49,
      rayonX: 2.59,
      rayonY: 0.99,
    },
    {
      type: 'INEGAUX',
      dimensions: '100x65x7',
      cote1: 100,
      cote2: 65,
      epaisseur: 7,
      poids: 8.77,
      section: 11.2,
      inertiex: 82.1,
      inertiey: 23.2,
      rayonX: 2.71,
      rayonY: 1.44,
    },
    {
      type: 'INEGAUX',
      dimensions: '100x75x8',
      cote1: 100,
      cote2: 75,
      epaisseur: 8,
      poids: 10.6,
      section: 13.5,
      inertiex: 103,
      inertiey: 35.0,
      rayonX: 2.76,
      rayonY: 1.61,
    },
    {
      type: 'INEGAUX',
      dimensions: '120x80x8',
      cote1: 120,
      cote2: 80,
      epaisseur: 8,
      poids: 12.3,
      section: 15.7,
      inertiex: 173,
      inertiey: 45.9,
      rayonX: 3.32,
      rayonY: 1.71,
    },
    {
      type: 'INEGAUX',
      dimensions: '150x75x9',
      cote1: 150,
      cote2: 75,
      epaisseur: 9,
      poids: 15.4,
      section: 19.6,
      inertiex: 332,
      inertiey: 34.8,
      rayonX: 4.11,
      rayonY: 1.33,
    },
    {
      type: 'INEGAUX',
      dimensions: '150x90x10',
      cote1: 150,
      cote2: 90,
      epaisseur: 10,
      poids: 18.2,
      section: 23.2,
      inertiex: 391,
      inertiey: 65.5,
      rayonX: 4.1,
      rayonY: 1.68,
    },
    {
      type: 'INEGAUX',
      dimensions: '200x100x10',
      cote1: 200,
      cote2: 100,
      epaisseur: 10,
      poids: 22.7,
      section: 28.9,
      inertiex: 925,
      inertiey: 92.0,
      rayonX: 5.66,
      rayonY: 1.78,
    },
    {
      type: 'INEGAUX',
      dimensions: '200x100x12',
      cote1: 200,
      cote2: 100,
      epaisseur: 12,
      poids: 27.0,
      section: 34.4,
      inertiex: 1078,
      inertiey: 106,
      rayonX: 5.6,
      rayonY: 1.76,
    },
  ]

  getFamilleInfo(): { famille: ArticleFamille; sousFamille: string } {
    return {
      famille: ArticleFamille.PROFILES_ACIER,
      sousFamille: 'CORNIERES',
    }
  }

  async generateArticles(): Promise<ArticleMetallurgie[]> {
    const articles: ArticleMetallurgie[] = []
    const materials = ['S235JR', 'S275JR', 'S355JR']

    for (const angle of this.angleSpecifications) {
      for (const material of materials) {
        const caracteristiques: CaracteristiquesTechniques = {
          largeur: angle.cote1,
          hauteur: angle.cote2,
          epaisseur: angle.epaisseur,
          poids: angle.poids,
          section: angle.section,
          momentInertieX: angle.inertiex,
          momentInertieY: angle.inertiey,
          rayonGirationX: angle.rayonX,
          rayonGirationY: angle.rayonY,
          moduleResistanceX: angle.inertiex / (angle.cote1 / 2 / 10), // conversion mm -> cm
          moduleResistanceY: angle.inertiey / (angle.cote2 / 2 / 10),
          nuance: material,
          norme: 'EN 10056-1',
          limiteElastique: this.getLimiteElastique(material),
          resistanceTraction: this.getResistanceTraction(material),
          allongement: this.getAllongement(material),
          applications: this.getApplications(angle.type),
          specifications: {
            typeProfile: 'ANGLE',
            typeCorniere: angle.type,
            dimensionsCommerciales: angle.dimensions,
            etatLivraison: 'Laminé à chaud',
            tolerances: 'Normales EN 10056-1',
          },
        }

        const article: ArticleMetallurgie = {
          reference: `L${angle.dimensions.replace(/[^a-zA-Z0-9]/g, '')}-${material}`,
          designation: `Cornière L${angle.dimensions} ${material}`,
          description: `Cornière ${angle.type === 'EGAUX' ? 'à ailes égales' : 'à ailes inégales'} L${angle.dimensions}, nuance ${material}, conforme EN 10056-1`,
          type: ArticleType.MATIERE_PREMIERE,
          status: ArticleStatus.ACTIF,
          famille: ArticleFamille.PROFILES_ACIER,
          sousFamille: 'CORNIERES',
          uniteStock: UniteStock.ML,
          uniteAchat: UniteStock.ML,
          uniteVente: UniteStock.ML,
          coefficientAchat: 1.0,
          coefficientVente: 1.0,
          gereEnStock: true,
          poids: angle.poids,
          caracteristiquesTechniques: caracteristiques,
          societeId: this.config.societeId,
        }

        this.calculatePricing(article)
        articles.push(article)
      }
    }

    this.logger.info(`${articles.length} articles cornières générés`)
    return articles
  }

  private getLimiteElastique(material: string): number {
    const limits: Record<string, number> = {
      S235JR: 235,
      S275JR: 275,
      S355JR: 355,
    }
    return limits[material] || 235
  }

  private getResistanceTraction(material: string): number {
    const resistances: Record<string, number> = {
      S235JR: 360,
      S275JR: 430,
      S355JR: 510,
    }
    return resistances[material] || 360
  }

  private getAllongement(material: string): number {
    const allongements: Record<string, number> = {
      S235JR: 26,
      S275JR: 22,
      S355JR: 22,
    }
    return allongements[material] || 26
  }

  private getApplications(type: string): string[] {
    const commonApps = [
      'Ossatures métalliques',
      'Charpentes légères',
      'Renforts et équerres',
      'Assemblages soudés',
      'Structures treillis',
    ]

    if (type === 'EGAUX') {
      return [...commonApps, 'Montants et traverses', 'Cadres symétriques', 'Pylônes et tours']
    } else {
      return [...commonApps, 'Linteaux et seuils', 'Supports asymétriques', 'Renforts spécifiques']
    }
  }
}
