/**
 * Injecteur pour profilés HEA et HEB
 * TopSteel ERP - Clean Architecture
 */

import { BaseArticleInjector } from '../core/base-article-injector'
import {
  ArticleFamille,
  type ArticleMetallurgie,
  ArticleStatus,
  ArticleType,
  type CaracteristiquesTechniques,
  UniteStock,
} from '../types/article-injection.types'

interface HeaHebProfile {
  serie: 'HEA' | 'HEB'
  dimension: string
  hauteur: number
  largeur: number
  epaisseurAme: number
  epaisseurAile: number
  poids: number
  section: number
  inertiex: number
  inertiey: number
  moduleX: number
  moduleY: number
  rayon: number
}

export class HeaHebProfilesInjector extends BaseArticleInjector {
  private readonly profiles: HeaHebProfile[] = [
    // Série HEA
    {
      serie: 'HEA',
      dimension: '100',
      hauteur: 96,
      largeur: 100,
      epaisseurAme: 5.0,
      epaisseurAile: 8.0,
      poids: 16.7,
      section: 21.2,
      inertiex: 349,
      inertiey: 134,
      moduleX: 72.6,
      moduleY: 26.8,
      rayon: 12,
    },
    {
      serie: 'HEA',
      dimension: '120',
      hauteur: 114,
      largeur: 120,
      epaisseurAme: 5.0,
      epaisseurAile: 8.0,
      poids: 19.9,
      section: 25.3,
      inertiex: 606,
      inertiey: 231,
      moduleX: 106,
      moduleY: 38.5,
      rayon: 12,
    },
    {
      serie: 'HEA',
      dimension: '140',
      hauteur: 133,
      largeur: 140,
      epaisseurAme: 5.5,
      epaisseurAile: 8.5,
      poids: 24.7,
      section: 31.4,
      inertiex: 1033,
      inertiey: 389,
      moduleX: 155,
      moduleY: 55.6,
      rayon: 12,
    },
    {
      serie: 'HEA',
      dimension: '160',
      hauteur: 152,
      largeur: 160,
      epaisseurAme: 6.0,
      epaisseurAile: 9.0,
      poids: 30.4,
      section: 38.8,
      inertiex: 1673,
      inertiey: 616,
      moduleX: 220,
      moduleY: 77.0,
      rayon: 15,
    },
    {
      serie: 'HEA',
      dimension: '180',
      hauteur: 171,
      largeur: 180,
      epaisseurAme: 6.0,
      epaisseurAile: 9.5,
      poids: 35.5,
      section: 45.3,
      inertiex: 2510,
      inertiey: 925,
      moduleX: 294,
      moduleY: 103,
      rayon: 15,
    },
    {
      serie: 'HEA',
      dimension: '200',
      hauteur: 190,
      largeur: 200,
      epaisseurAme: 6.5,
      epaisseurAile: 10.0,
      poids: 42.3,
      section: 53.8,
      inertiex: 3692,
      inertiey: 1336,
      moduleX: 389,
      moduleY: 134,
      rayon: 18,
    },
    {
      serie: 'HEA',
      dimension: '220',
      hauteur: 210,
      largeur: 220,
      epaisseurAme: 7.0,
      epaisseurAile: 11.0,
      poids: 50.5,
      section: 64.3,
      inertiex: 5410,
      inertiey: 1955,
      moduleX: 515,
      moduleY: 178,
      rayon: 18,
    },
    {
      serie: 'HEA',
      dimension: '240',
      hauteur: 230,
      largeur: 240,
      epaisseurAme: 7.5,
      epaisseurAile: 12.0,
      poids: 60.3,
      section: 76.8,
      inertiex: 7763,
      inertiey: 2769,
      moduleX: 675,
      moduleY: 231,
      rayon: 21,
    },
    {
      serie: 'HEA',
      dimension: '260',
      hauteur: 250,
      largeur: 260,
      epaisseurAme: 7.5,
      epaisseurAile: 12.5,
      poids: 68.2,
      section: 86.8,
      inertiex: 10450,
      inertiey: 3668,
      moduleX: 836,
      moduleY: 282,
      rayon: 24,
    },
    {
      serie: 'HEA',
      dimension: '280',
      hauteur: 270,
      largeur: 280,
      epaisseurAme: 8.0,
      epaisseurAile: 13.0,
      poids: 76.4,
      section: 97.3,
      inertiex: 13670,
      inertiey: 4763,
      moduleX: 1013,
      moduleY: 340,
      rayon: 24,
    },
    {
      serie: 'HEA',
      dimension: '300',
      hauteur: 290,
      largeur: 300,
      epaisseurAme: 8.5,
      epaisseurAile: 14.0,
      poids: 88.3,
      section: 113,
      inertiex: 18260,
      inertiey: 6310,
      moduleX: 1260,
      moduleY: 420,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '320',
      hauteur: 310,
      largeur: 300,
      epaisseurAme: 9.0,
      epaisseurAile: 15.5,
      poids: 97.6,
      section: 124,
      inertiex: 22930,
      inertiey: 6985,
      moduleX: 1479,
      moduleY: 466,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '340',
      hauteur: 330,
      largeur: 300,
      epaisseurAme: 9.5,
      epaisseurAile: 16.5,
      poids: 105,
      section: 134,
      inertiex: 27690,
      inertiey: 7436,
      moduleX: 1678,
      moduleY: 496,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '360',
      hauteur: 350,
      largeur: 300,
      epaisseurAme: 10.0,
      epaisseurAile: 17.5,
      poids: 112,
      section: 143,
      inertiex: 32720,
      inertiey: 7887,
      moduleX: 1869,
      moduleY: 526,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '400',
      hauteur: 390,
      largeur: 300,
      epaisseurAme: 11.0,
      epaisseurAile: 19.0,
      poids: 125,
      section: 159,
      inertiex: 41570,
      inertiey: 8564,
      moduleX: 2134,
      moduleY: 571,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '450',
      hauteur: 440,
      largeur: 300,
      epaisseurAme: 11.5,
      epaisseurAile: 21.0,
      poids: 140,
      section: 178,
      inertiex: 57680,
      inertiey: 9462,
      moduleX: 2622,
      moduleY: 631,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '500',
      hauteur: 490,
      largeur: 300,
      epaisseurAme: 12.0,
      epaisseurAile: 23.0,
      poids: 155,
      section: 198,
      inertiex: 75920,
      inertiey: 10368,
      moduleX: 3099,
      moduleY: 691,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '550',
      hauteur: 540,
      largeur: 300,
      epaisseurAme: 12.5,
      epaisseurAile: 24.0,
      poids: 166,
      section: 212,
      inertiex: 94980,
      inertiey: 10819,
      moduleX: 3518,
      moduleY: 721,
      rayon: 27,
    },
    {
      serie: 'HEA',
      dimension: '600',
      hauteur: 590,
      largeur: 300,
      epaisseurAme: 13.0,
      epaisseurAile: 25.0,
      poids: 178,
      section: 226,
      inertiex: 115500,
      inertiey: 11270,
      moduleX: 3915,
      moduleY: 751,
      rayon: 27,
    },

    // Série HEB
    {
      serie: 'HEB',
      dimension: '100',
      hauteur: 100,
      largeur: 100,
      epaisseurAme: 6.0,
      epaisseurAile: 10.0,
      poids: 20.4,
      section: 26.0,
      inertiex: 450,
      inertiey: 167,
      moduleX: 89.9,
      moduleY: 33.5,
      rayon: 12,
    },
    {
      serie: 'HEB',
      dimension: '120',
      hauteur: 120,
      largeur: 120,
      epaisseurAme: 6.5,
      epaisseurAile: 11.0,
      poids: 26.7,
      section: 34.0,
      inertiex: 864,
      inertiey: 318,
      moduleX: 144,
      moduleY: 52.9,
      rayon: 12,
    },
    {
      serie: 'HEB',
      dimension: '140',
      hauteur: 140,
      largeur: 140,
      epaisseurAme: 7.0,
      epaisseurAile: 12.0,
      poids: 33.7,
      section: 43.0,
      inertiex: 1509,
      inertiey: 549,
      moduleX: 216,
      moduleY: 78.4,
      rayon: 12,
    },
    {
      serie: 'HEB',
      dimension: '160',
      hauteur: 160,
      largeur: 160,
      epaisseurAme: 8.0,
      epaisseurAile: 13.0,
      poids: 42.6,
      section: 54.3,
      inertiex: 2492,
      inertiey: 889,
      moduleX: 311,
      moduleY: 111,
      rayon: 15,
    },
    {
      serie: 'HEB',
      dimension: '180',
      hauteur: 180,
      largeur: 180,
      epaisseurAme: 8.5,
      epaisseurAile: 14.0,
      poids: 51.2,
      section: 65.3,
      inertiex: 3831,
      inertiey: 1363,
      moduleX: 426,
      moduleY: 152,
      rayon: 15,
    },
    {
      serie: 'HEB',
      dimension: '200',
      hauteur: 200,
      largeur: 200,
      epaisseurAme: 9.0,
      epaisseurAile: 15.0,
      poids: 61.3,
      section: 78.1,
      inertiex: 5696,
      inertiey: 2003,
      moduleX: 570,
      moduleY: 200,
      rayon: 18,
    },
    {
      serie: 'HEB',
      dimension: '220',
      hauteur: 220,
      largeur: 220,
      epaisseurAme: 9.5,
      epaisseurAile: 16.0,
      poids: 71.5,
      section: 91.0,
      inertiex: 8091,
      inertiey: 2843,
      moduleX: 736,
      moduleY: 258,
      rayon: 18,
    },
    {
      serie: 'HEB',
      dimension: '240',
      hauteur: 240,
      largeur: 240,
      epaisseurAme: 10.0,
      epaisseurAile: 17.0,
      poids: 83.2,
      section: 106,
      inertiex: 11260,
      inertiey: 3923,
      moduleX: 938,
      moduleY: 327,
      rayon: 21,
    },
    {
      serie: 'HEB',
      dimension: '260',
      hauteur: 260,
      largeur: 260,
      epaisseurAme: 10.0,
      epaisseurAile: 17.5,
      poids: 93.0,
      section: 118,
      inertiex: 14920,
      inertiey: 5135,
      moduleX: 1148,
      moduleY: 395,
      rayon: 24,
    },
    {
      serie: 'HEB',
      dimension: '280',
      hauteur: 280,
      largeur: 280,
      epaisseurAme: 10.5,
      epaisseurAile: 18.0,
      poids: 103,
      section: 131,
      inertiex: 19270,
      inertiey: 6595,
      moduleX: 1376,
      moduleY: 471,
      rayon: 24,
    },
    {
      serie: 'HEB',
      dimension: '300',
      hauteur: 300,
      largeur: 300,
      epaisseurAme: 11.0,
      epaisseurAile: 19.0,
      poids: 117,
      section: 149,
      inertiex: 25170,
      inertiey: 8563,
      moduleX: 1678,
      moduleY: 571,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '320',
      hauteur: 320,
      largeur: 300,
      epaisseurAme: 11.5,
      epaisseurAile: 20.5,
      poids: 127,
      section: 161,
      inertiex: 30820,
      inertiey: 9239,
      moduleX: 1926,
      moduleY: 616,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '340',
      hauteur: 340,
      largeur: 300,
      epaisseurAme: 12.0,
      epaisseurAile: 21.5,
      poids: 134,
      section: 171,
      inertiex: 36660,
      inertiey: 9690,
      moduleX: 2156,
      moduleY: 646,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '360',
      hauteur: 360,
      largeur: 300,
      epaisseurAme: 12.5,
      epaisseurAile: 22.5,
      poids: 142,
      section: 181,
      inertiex: 43190,
      inertiey: 10140,
      moduleX: 2399,
      moduleY: 676,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '400',
      hauteur: 400,
      largeur: 300,
      epaisseurAme: 13.5,
      epaisseurAile: 24.0,
      poids: 155,
      section: 197,
      inertiex: 57680,
      inertiey: 10819,
      moduleX: 2884,
      moduleY: 721,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '450',
      hauteur: 450,
      largeur: 300,
      epaisseurAme: 14.0,
      epaisseurAile: 26.0,
      poids: 171,
      section: 218,
      inertiex: 79890,
      inertiey: 11720,
      moduleX: 3551,
      moduleY: 781,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '500',
      hauteur: 500,
      largeur: 300,
      epaisseurAme: 14.5,
      epaisseurAile: 28.0,
      poids: 187,
      section: 239,
      inertiex: 107200,
      inertiey: 12620,
      moduleX: 4287,
      moduleY: 841,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '550',
      hauteur: 550,
      largeur: 300,
      epaisseurAme: 15.0,
      epaisseurAile: 29.0,
      poids: 199,
      section: 254,
      inertiex: 136700,
      inertiey: 13070,
      moduleX: 4971,
      moduleY: 871,
      rayon: 27,
    },
    {
      serie: 'HEB',
      dimension: '600',
      hauteur: 600,
      largeur: 300,
      epaisseurAme: 15.5,
      epaisseurAile: 30.0,
      poids: 212,
      section: 270,
      inertiex: 171000,
      inertiey: 13520,
      moduleX: 5701,
      moduleY: 901,
      rayon: 27,
    },
  ]

  getFamilleInfo(): { famille: ArticleFamille; sousFamille: string } {
    return {
      famille: ArticleFamille.PROFILES_ACIER,
      sousFamille: 'HEA_HEB',
    }
  }

  async generateArticles(): Promise<ArticleMetallurgie[]> {
    const articles: ArticleMetallurgie[] = []
    const materials = ['S235JR', 'S275JR', 'S355JR']

    for (const profile of this.profiles) {
      for (const material of materials) {
        const caracteristiques: CaracteristiquesTechniques = {
          hauteur: profile.hauteur,
          largeur: profile.largeur,
          epaisseurAme: profile.epaisseurAme,
          epaisseurAile: profile.epaisseurAile,
          poids: profile.poids,
          section: profile.section,
          momentInertieX: profile.inertiex,
          momentInertieY: profile.inertiey,
          moduleResistanceX: profile.moduleX,
          moduleResistanceY: profile.moduleY,
          rayonGirationX: Math.sqrt(profile.inertiex / profile.section),
          rayonGirationY: Math.sqrt(profile.inertiey / profile.section),
          nuance: material,
          norme: 'EN 10025-2',
          limiteElastique: this.getLimiteElastique(material),
          resistanceTraction: this.getResistanceTraction(material),
          allongement: this.getAllongement(material),
          applications: this.getApplications(profile.serie),
          specifications: {
            typeProfile: profile.serie,
            dimension: profile.dimension,
            rayonConge: profile.rayon,
            serieProfil: profile.serie === 'HEA' ? 'légère' : 'lourde',
          },
        }

        const article: ArticleMetallurgie = {
          reference: `${profile.serie}${profile.dimension}-${material}`,
          designation: `Poutre ${profile.serie} ${profile.dimension} ${material}`,
          description: `Poutre ${profile.serie} ${profile.dimension}mm, nuance ${material}, conforme EN 10025-2 - ${profile.serie === 'HEA' ? 'série légère' : 'série lourde'}`,
          type: ArticleType.MATIERE_PREMIERE,
          status: ArticleStatus.ACTIF,
          famille: ArticleFamille.PROFILES_ACIER,
          sousFamille: profile.serie,
          uniteStock: UniteStock.ML,
          uniteAchat: UniteStock.ML,
          uniteVente: UniteStock.ML,
          coefficientAchat: 1.0,
          coefficientVente: 1.0,
          gereEnStock: true,
          poids: profile.poids,
          caracteristiquesTechniques: caracteristiques,
          societeId: this.config.societeId,
        }

        this.calculatePricing(article)
        articles.push(article)
      }
    }

    this.logger.info(`${articles.length} articles profilés HEA/HEB générés`)
    return articles
  }

  private getLimiteElastique(material: string): number {
    const limits: Record<string, number> = {
      S235JR: 235,
      S275JR: 275,
      S355JR: 355,
    }
    return limits[material] || 235
  }

  private getResistanceTraction(material: string): number {
    const resistances: Record<string, number> = {
      S235JR: 360,
      S275JR: 430,
      S355JR: 510,
    }
    return resistances[material] || 360
  }

  private getAllongement(material: string): number {
    const allongements: Record<string, number> = {
      S235JR: 26,
      S275JR: 22,
      S355JR: 22,
    }
    return allongements[material] || 26
  }

  private getApplications(serie: string): string[] {
    if (serie === 'HEA') {
      return [
        'Charpente légère',
        'Poteaux légers',
        'Poutres secondaires',
        'Ossatures bâtiments',
        'Structures courantes',
      ]
    } else {
      return [
        'Charpente lourde',
        'Poteaux principaux',
        'Poutres maîtresses',
        'Structures industrielles',
        "Ponts et ouvrages d'art",
        'Charges importantes',
      ]
    }
  }
}
