# .github/dependabot.yml
version: 2
updates:
  # Configuration pour les dépendances npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "*test*"
    reviewers:
      - "Symple44"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignorer les mises à jour majeures pour certains packages critiques
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@nestjs/*"
        update-types: ["version-update:semver-major"]

  # Configuration pour les GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "Symple44"
    labels:
      - "ci/cd"
      - "automated"
    commit-message:
      prefix: "ci"
