# .github/dependabot.yml
version: 2
updates:
  # Configuration pour les dépendances npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "*test*"
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignorer les mises à jour majeures pour certains packages critiques
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@nestjs/*"
        update-types: ["version-update:semver-major"]

  # Configuration pour les GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "your-github-username"
    labels:
      - "ci/cd"
      - "automated"
    commit-message:
      prefix: "ci"

---
# .github/pull_request_template.md
## Description
<!-- Décrivez brièvement les changements apportés -->

## Type de changement
- [ ] 🐛 Bug fix (changement non-breaking qui corrige un problème)
- [ ] ✨ Nouvelle fonctionnalité (changement non-breaking qui ajoute une fonctionnalité)
- [ ] 💥 Breaking change (changement qui pourrait casser la compatibilité)
- [ ] 📝 Documentation
- [ ] 🎨 Style/UI
- [ ] ♻️ Refactoring
- [ ] ⚡ Performance
- [ ] ✅ Tests
- [ ] 🔧 Configuration
- [ ] 🔐 Sécurité

## Checklist
- [ ] Mon code suit les conventions du projet
- [ ] J'ai effectué une auto-review de mon code
- [ ] J'ai commenté mon code, particulièrement dans les parties complexes
- [ ] J'ai mis à jour la documentation si nécessaire
- [ ] Mes changements ne génèrent pas de nouveaux warnings
- [ ] J'ai ajouté des tests qui prouvent que ma correction/fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement
- [ ] J'ai vérifié que ma branche est à jour avec `develop`/`main`

## Tests effectués
<!-- Décrivez les tests que vous avez effectués pour vérifier vos changements -->

## Screenshots (si applicable)
<!-- Ajoutez des captures d'écran pour illustrer les changements visuels -->

## Notes pour les reviewers
<!-- Ajoutez des notes spécifiques pour aider les reviewers -->

---
# .github/ISSUE_TEMPLATE/bug_report.yml
name: 🐛 Bug Report
description: Signaler un bug dans l'application
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug ! 
        Veuillez remplir le formulaire ci-dessous avec autant de détails que possible.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug
      placeholder: "Décrivez le bug ici..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Étapes pour reproduire le comportement
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Faire défiler jusqu'à '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Une description claire de ce que vous attendiez
      placeholder: "Je m'attendais à ce que..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Ce qui se passe réellement
      placeholder: "Au lieu de cela, il se passe..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Sévérité
      description: Quelle est la gravité de ce bug ?
      options:
        - Critique (bloque complètement l'utilisation)
        - Majeur (fonctionnalité importante cassée)
        - Mineur (problème cosmétique ou mineur)
        - Trivial
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module affecté
      description: Quel module est affecté ?
      options:
        - Frontend (Web)
        - Backend (API)
        - Base de données
        - UI Components
        - Utils
        - Types
        - CI/CD
        - Documentation
        - Autre
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: Informations sur votre environnement
      placeholder: |
        - OS: [e.g. Windows 11, macOS 14, Ubuntu 22.04]
        - Navigateur: [e.g. Chrome 120, Firefox 121]
        - Version Node.js: [e.g. 18.17.0]
        - Version pnpm: [e.g. 8.15.0]
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoutez des captures d'écran
      placeholder: "Glissez-déposez vos images ici"

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Logs pertinents (erreurs console, logs serveur, etc.)
      render: shell
      placeholder: "Collez les logs ici..."

  - type: textarea
    id: additional
    attributes:
      label: Contexte additionnel
      description: Toute autre information pertinente
      placeholder: "Informations supplémentaires..."

---
# .github/ISSUE_TEMPLATE/feature_request.yml
name: ✨ Feature Request
description: Suggérer une nouvelle fonctionnalité
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Merci de proposer une nouvelle fonctionnalité !
        Veuillez fournir autant de détails que possible.

  - type: textarea
    id: problem
    attributes:
      label: Problème à résoudre
      description: Décrivez le problème que cette fonctionnalité résoudrait
      placeholder: "Je suis frustré quand..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Décrivez comment vous imaginez cette fonctionnalité
      placeholder: "J'aimerais pouvoir..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considérées
      description: Avez-vous envisagé d'autres solutions ?
      placeholder: "J'ai aussi pensé à..."

  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      description: Quelle est l'importance de cette fonctionnalité pour vous ?
      options:
        - Critique (bloquant pour mon utilisation)
        - Haute (très important)
        - Moyenne (serait bien à avoir)
        - Basse (nice to have)
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module concerné
      description: Quel module serait affecté ?
      multiple: true
      options:
        - Frontend (Web)
        - Backend (API)
        - Base de données
        - UI Components
        - Utils
        - Types
        - Nouveau module
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Seriez-vous prêt à contribuer ?
      options:
        - label: Je suis prêt à implémenter cette fonctionnalité
        - label: Je peux aider avec les tests
        - label: Je peux aider avec la documentation

  - type: textarea
    id: mockups
    attributes:
      label: Maquettes / Exemples
      description: Si applicable, ajoutez des maquettes ou exemples
      placeholder: "Ajoutez des images ou du code exemple..."

---
# .github/workflows/pr-checks.yml
name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  # Vérification de la taille de la PR
  pr-size:
    name: Check PR Size
    runs-on: ubuntu-latest
    steps:
      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions;
            const deletions = pr.deletions;
            const total = additions + deletions;
            
            let label = '';
            if (total < 10) label = 'size/XS';
            else if (total < 50) label = 'size/S';
            else if (total < 200) label = 'size/M';
            else if (total < 500) label = 'size/L';
            else label = 'size/XL';
            
            // Ajouter le label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: [label]
            });
            
            // Avertir si la PR est trop grande
            if (total > 500) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: '⚠️ Cette PR contient plus de 500 lignes de changements. Considérez la diviser en PRs plus petites pour faciliter la review.'
              });
            }

  # Auto-labeling basé sur les fichiers modifiés
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

  # Vérification des commits conventionnels
  commitlint:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json

  # Analyse des fichiers modifiés
  changed-files:
    name: Analyze Changed Files
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.changes.outputs.web }}
      api: ${{ steps.changes.outputs.api }}
      packages: ${{ steps.changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            web:
              - 'apps/web/**'
            api:
              - 'apps/api/**'
            packages:
              - 'packages/**'
      
      - name: Comment changed areas
        uses: actions/github-script@v7
        with:
          script: |
            const changes = {
              web: ${{ steps.changes.outputs.web }},
              api: ${{ steps.changes.outputs.api }},
              packages: ${{ steps.changes.outputs.packages }}
            };
            
            const affected = Object.entries(changes)
              .filter(([_, changed]) => changed === 'true')
              .map(([area, _]) => area);
            
            if (affected.length > 0) {
              const body = `📦 **Zones affectées**: ${affected.join(', ')}`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body
              });
            }

---
# .github/workflows/codeql.yml
name: CodeQL Analysis

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 2 * * 1' # Tous les lundis à 2h du matin

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'typescript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-extended,security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

---
# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm (if applicable)
        if: false # À activer si vous publiez sur npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          pnpm publish --access public --no-git-checks