# .github/dependabot.yml
version: 2
updates:
  # Configuration pour les dépendances npm (racine du monorepo)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      # Grouper les mises à jour de sécurité (priorité haute)
      security:
        applies-to: security-updates
        patterns:
          - "*"
      # Grouper les dépendances de production
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # Grouper les dépendances de développement
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "@biomejs/*"
          - "vitest*"
          - "turbo"
      # Grouper les packages Radix UI
      radix-ui:
        patterns:
          - "@radix-ui/*"
      # Grouper les packages TanStack
      tanstack:
        patterns:
          - "@tanstack/*"
    reviewers:
      - "Symple44"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignorer les mises à jour majeures pour certains packages critiques
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@nestjs/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typeorm"
        update-types: ["version-update:semver-major"]

  # Configuration pour les GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "Symple44"
    labels:
      - "ci/cd"
      - "automated"
    commit-message:
      prefix: "ci"
