apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-api-blue
  namespace: topsteel-marketplace
  labels:
    app: marketplace-api
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marketplace-api
      version: blue
  template:
    metadata:
      labels:
        app: marketplace-api
        version: blue
    spec:
      containers:
      - name: api
        image: ghcr.io/topsteel/marketplace-api:stable
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEPLOYMENT_VERSION
          value: "blue"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-web-blue
  namespace: topsteel-marketplace
  labels:
    app: marketplace-web
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marketplace-web
      version: blue
  template:
    metadata:
      labels:
        app: marketplace-web
        version: blue
    spec:
      containers:
      - name: web
        image: ghcr.io/topsteel/marketplace-web:stable
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEPLOYMENT_VERSION
          value: "blue"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-api-blue-service
  namespace: topsteel-marketplace
spec:
  selector:
    app: marketplace-api
    version: blue
  ports:
  - port: 3001
    targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-web-blue-service
  namespace: topsteel-marketplace
spec:
  selector:
    app: marketplace-web
    version: blue
  ports:
  - port: 3000
    targetPort: 3000