// packages/types/src/constants.ts
export const DEVIS_STATUT = {
  BROUILLON: 'BROUILLON',
  DEVIS: 'DEVIS',
  ENVOYE: 'ENVOYE',
  ACCEPTE: 'ACCEPTE',
  REFUSE: 'REFUSE'
} as const

export const PROJET_STATUT = {
  NOUVEAU: 'NOUVEAU',
  DEVIS: 'DEVIS',
  EN_COURS: 'EN_COURS',
  TERMINE: 'TERMINE',
  ANNULE: 'ANNULE',
  EN_ATTENTE: 'EN_ATTENTE'
} as const

export const STATUT_PRODUCTION = {
  EN_ATTENTE: 'EN_ATTENTE',
  PLANIFIE: 'PLANIFIE', 
  EN_COURS: 'EN_COURS',
  TERMINE: 'TERMINE',
  ANNULE: 'ANNULE',
  PAUSE: 'PAUSE'
} as const

export const PRIORITE_PRODUCTION = {
  BASSE: 'BASSE',
  NORMALE: 'NORMALE',
  HAUTE: 'HAUTE',
  URGENTE: 'URGENTE'
} as const
