#!/bin/bash
# Auto-generated script to delete duplicate TypeORM entities
# Review carefully before executing!

echo "🗑️  Deleting duplicate TypeORM entities..."
echo ""

echo "Deleting: audit-log.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\audit-log.entity.ts"
echo "Deleting: discovered-page.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\menu\entities\discovered-page.entity.ts"
echo "Deleting: group.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\group.entity.ts"
echo "Deleting: menu-configuration.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\admin\entities\menu-configuration.entity.ts"
echo "Deleting: menu-configuration.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entities\menu-configuration.entity.ts"
echo "Deleting: menu-configuration-simple.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entities\menu-configuration-simple.entity.ts"
echo "Deleting: menu-item.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\admin\entities\menu-item.entity.ts"
echo "Deleting: menu-item.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entities\menu-item.entity.ts"
echo "Deleting: menu-item-permission.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entities\menu-item-permission.entity.ts"
echo "Deleting: menu-item-role.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entities\menu-item-role.entity.ts"
echo "Deleting: mfa-session.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\mfa-session.entity.ts"
echo "Deleting: module.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\module.entity.ts"
echo "Deleting: notification-event.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\notifications\entities\notification-event.entity.ts"
echo "Deleting: notification-read.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\notifications\entities\notification-read.entity.ts"
echo "Deleting: notification-rule.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\notifications\entities\notification-rule.entity.ts"
echo "Deleting: notification-rule.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\notifications\entities\notification-rule.entity.ts"
echo "Deleting: notification-rule-execution.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\notifications\entities\notification-rule-execution.entity.ts"
echo "Deleting: notification-settings.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\notifications\entities\notification-settings.entity.ts"
echo "Deleting: notification-template.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\notifications\entities\notification-template.entity.ts"
echo "Deleting: parameter-application.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\parameters\entities\parameter-application.entity.ts"
echo "Deleting: parameter-client.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\parameters\entities\parameter-client.entity.ts"
echo "Deleting: parameter-system.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\parameters\entities\parameter-system.entity.ts"
echo "Deleting: permission.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\permission.entity.ts"
echo "Deleting: query-builder.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\query-builder\entities\query-builder.entity.ts"
echo "Deleting: query-builder-calculated-field.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\query-builder\entities\query-builder-calculated-field.entity.ts"
echo "Deleting: query-builder-column.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\query-builder\entities\query-builder-column.entity.ts"
echo "Deleting: query-builder-join.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\query-builder\entities\query-builder-join.entity.ts"
echo "Deleting: query-builder-permission.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\query-builder\entities\query-builder-permission.entity.ts"
echo "Deleting: role.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\role.entity.ts"
echo "Deleting: role-permission.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\role-permission.entity.ts"
echo "Deleting: site.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\societes\entities\site.entity.ts"
echo "Deleting: sms-log.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\entities\sms-log.entity.ts"
echo "Deleting: societe.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\societes\entities\societe.entity.ts"
echo "Deleting: societe-license.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\societes\entities\societe-license.entity.ts"
echo "Deleting: societe-user.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\societes\entities\societe-user.entity.ts"
echo "Deleting: system-parameter.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entitites\system-parameter.entity.ts"
echo "Deleting: system-setting.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entitites\system-setting.entity.ts"
echo "Deleting: user.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\users\entities\user.entity.ts"
echo "Deleting: user-group.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\user-group.entity.ts"
echo "Deleting: user-menu-item-preference.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entities\user-menu-item-preference.entity.ts"
echo "Deleting: user-menu-preference.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\admin\entities\user-menu-preference.entity.ts"
echo "Deleting: user-menu-preference.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\menu\entities\user-menu-preference.entity.ts"
echo "Deleting: user-menu-preferences.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\features\admin\entities\user-menu-preferences.entity.ts"
echo "Deleting: user-mfa.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\user-mfa.entity.ts"
echo "Deleting: user-role.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\user-role.entity.ts"
echo "Deleting: user-session.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\user-session.entity.ts"
echo "Deleting: user-settings.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\users\entities\user-settings.entity.ts"
echo "Deleting: user-societe-role.entity.ts"
rm "C:\GitHub\TopSteel\apps\api\src\domains\auth\core\entities\user-societe-role.entity.ts"

echo ""
echo "✅ Deletion complete!"
echo "   Deleted: 48 files"