@echo off
REM Script to restore critical TypeORM entities from commit before Phase 1
REM Generated by analyze-typeorm-usage.js

echo.
echo ========================================
echo Restoring critical TypeORM entities...
echo ========================================
echo.

set COMMIT=f024017b~1

REM Auth domain entities
echo [1/35] Restoring user.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/users/entities/user.entity.ts

echo [2/35] Restoring role.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/role.entity.ts

echo [3/35] Restoring permission.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/permission.entity.ts

echo [4/35] Restoring user-session.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/user-session.entity.ts

echo [5/35] Restoring mfa-session.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/mfa-session.entity.ts

echo [6/35] Restoring user-mfa.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/user-mfa.entity.ts

echo [7/35] Restoring audit-log.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/audit-log.entity.ts

echo [8/35] Restoring group.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/group.entity.ts

echo [9/35] Restoring user-group.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/user-group.entity.ts

echo [10/35] Restoring role-permission.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/role-permission.entity.ts

echo [11/35] Restoring user-role.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/user-role.entity.ts

echo [12/35] Restoring user-societe-role.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/user-societe-role.entity.ts

echo [13/35] Restoring module.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/core/entities/module.entity.ts

echo [14/35] Restoring sms-log.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/auth/entities/sms-log.entity.ts

REM Admin/Menu entities - domains
echo [15/35] Restoring menu-configuration.entity.ts (domains/admin)...
git checkout %COMMIT% -- apps/api/src/domains/admin/entities/menu-configuration.entity.ts

echo [16/35] Restoring menu-item.entity.ts (domains/admin)...
git checkout %COMMIT% -- apps/api/src/domains/admin/entities/menu-item.entity.ts

echo [17/35] Restoring user-menu-preference.entity.ts (domains/admin)...
git checkout %COMMIT% -- apps/api/src/domains/admin/entities/user-menu-preference.entity.ts

REM Admin/Menu entities - features
echo [18/35] Restoring menu-item-role.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/admin/entities/menu-item-role.entity.ts

echo [19/35] Restoring menu-item-permission.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/admin/entities/menu-item-permission.entity.ts

echo [20/35] Restoring user-menu-item-preference.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/admin/entities/user-menu-item-preference.entity.ts

echo [21/35] Restoring user-menu-preferences.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/admin/entities/user-menu-preferences.entity.ts

echo [22/35] Restoring menu-configuration-simple.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/admin/entities/menu-configuration-simple.entity.ts

echo [23/35] Restoring system-parameter.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/admin/entitites/system-parameter.entity.ts

echo [24/35] Restoring system-setting.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/admin/entitites/system-setting.entity.ts

echo [25/35] Restoring discovered-page.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/menu/entities/discovered-page.entity.ts

REM Notification entities
echo [26/35] Restoring notification-rule.entity.ts (domains/notifications)...
git checkout %COMMIT% -- apps/api/src/domains/notifications/entities/notification-rule.entity.ts

echo [27/35] Restoring notification-settings.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/notifications/entities/notification-settings.entity.ts

REM User entities
echo [28/35] Restoring user-settings.entity.ts...
git checkout %COMMIT% -- apps/api/src/domains/users/entities/user-settings.entity.ts

REM Parameter entities
echo [29/35] Restoring parameter-application.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/parameters/entities/parameter-application.entity.ts

echo [30/35] Restoring parameter-client.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/parameters/entities/parameter-client.entity.ts

echo [31/35] Restoring parameter-system.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/parameters/entities/parameter-system.entity.ts

REM Societe entities
echo [32/35] Restoring societe.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/societes/entities/societe.entity.ts

echo [33/35] Restoring societe-user.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/societes/entities/societe-user.entity.ts

echo [34/35] Restoring societe-license.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/societes/entities/societe-license.entity.ts

echo [35/35] Restoring site.entity.ts...
git checkout %COMMIT% -- apps/api/src/features/societes/entities/site.entity.ts

echo.
echo ========================================
echo Restoration complete!
echo ========================================
echo.
echo Next step: Clean duplicate imports
echo   node apps/api/scripts/cleanup-duplicate-imports.js
echo.
