#!/usr/bin/env ts-node
/**
 * Script de nettoyage forcé pour supprimer l'index problématique
 * Usage: npm run db:force-cleanup
 */

import { DataSource } from 'typeorm'
import { Logger } from '@nestjs/common'
import * as dotenv from 'dotenv'
import * as path from 'path'

// Charger les variables d'environnement
dotenv.config({ path: path.join(__dirname, '../../../../.env.local') })

const logger = new Logger('ForceCleanup')

async function forceCleanupIndex() {
  const dataSource = new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432'),
    username: process.env.DB_USERNAME || 'postgres',
    password: process.env.DB_PASSWORD || 'postgres',
    database: process.env.DB_NAME || 'erp_topsteel',
  })

  try {
    await dataSource.initialize()
    logger.log('✅ Connexion à la base de données établie')

    // Supprimer directement l'index problématique
    const problematicIndex = 'IDX_e4a5a4bcd15ca9eedd81916638'
    
    logger.log(`🔥 Suppression forcée de l'index ${problematicIndex}`)
    
    // Vérifier si l'index existe
    const indexExists = await dataSource.query(`
      SELECT 1 FROM pg_indexes 
      WHERE indexname = $1 
      AND schemaname = 'public'
    `, [problematicIndex])
    
    if (indexExists.length > 0) {
      logger.log(`🔍 Index trouvé, suppression en cours...`)
      
      // Supprimer l'index de force
      await dataSource.query(`DROP INDEX IF EXISTS "${problematicIndex}" CASCADE`)
      logger.log(`✅ Index ${problematicIndex} supprimé avec succès`)
      
      // Vérifier la suppression
      const stillExists = await dataSource.query(`
        SELECT 1 FROM pg_indexes 
        WHERE indexname = $1 
        AND schemaname = 'public'
      `, [problematicIndex])
      
      if (stillExists.length === 0) {
        logger.log(`✅ Confirmation: l'index n'existe plus`)
      } else {
        logger.error(`❌ L'index persiste encore!`)
      }
    } else {
      logger.log(`ℹ️  L'index n'existe pas dans la base`)
    }
    
    // Supprimer également la table user_menu_preferences_admin si elle existe
    logger.log(`🔥 Suppression forcée de la table user_menu_preferences_admin`)
    
    const tableExists = await dataSource.query(`
      SELECT 1 FROM information_schema.tables 
      WHERE table_name = 'user_menu_preferences_admin' 
      AND table_schema = 'public'
    `)
    
    if (tableExists.length > 0) {
      await dataSource.query(`DROP TABLE IF EXISTS "user_menu_preferences_admin" CASCADE`)
      logger.log(`✅ Table user_menu_preferences_admin supprimée`)
    } else {
      logger.log(`ℹ️  La table n'existe pas`)
    }
    
    // Supprimer tous les index TypeORM auto-générés
    logger.log(`🧹 Nettoyage des index auto-générés`)
    
    const autoGeneratedIndexes = await dataSource.query(`
      SELECT indexname
      FROM pg_indexes
      WHERE schemaname = 'public'
      AND indexname LIKE 'IDX_%'
      AND length(indexname) BETWEEN 30 AND 34
    `)
    
    for (const { indexname } of autoGeneratedIndexes) {
      try {
        await dataSource.query(`DROP INDEX IF EXISTS "${indexname}" CASCADE`)
        logger.log(`✅ Index auto-généré ${indexname} supprimé`)
      } catch (error) {
        logger.warn(`⚠️  Impossible de supprimer ${indexname}:`, error instanceof Error ? error.message : String(error))
      }
    }
    
    logger.log(`🎉 Nettoyage forcé terminé avec succès!`)
    logger.log(`Vous pouvez maintenant redémarrer l'application.`)
    
    await dataSource.destroy()
    process.exit(0)
  } catch (error) {
    logger.error('❌ Erreur lors du nettoyage forcé:', error)
    process.exit(1)
  }
}

forceCleanupIndex()